apiVersion: v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
    metadata:
       labels:
         app: app1
    spec:
      containers:s
      - name: app1
        image: nginx
        ports:
        - containerPort: 80
