apiVersion: v1
kind: Service
metadata:
  name: {{ template "monitoring-stack.fullname" . }}-grafana
  labels:
    app: {{ template "monitoring-stack.name" . }}-grafana
    chart: {{ template "monitoring-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: 30999
      name: http
  selector:
    app: {{ template "monitoring-stack.name" . }}-grafana
    release: {{ .Release.Name }}
